version: '3'
services:
  cyberus:
    image: cyberus:1.0
    build: .
    ports:
    - "8080:8081"
    - "4200:4200"
    - "49153:49153"
    volumes:
    - ./server/container:/app/server
    - ./cyberus/container:/app/cyberus